"""shadow_tracker.py — Phase 3B.7 (stabilized, Phase 3B.9S)

Paper-trading valuation engine for ShadowPortfolio rows.

Two shadow types:
  STATIC_FROZEN — Holdings frozen at the moment a UserExecutionDecision was
                  recorded.  Simulates "what would have happened if the user
                  had followed the recommendation exactly."
  ACTIVE_MODEL  — Hypothetical 100%-compliant portfolio rebuilt each time the
                  optimizer runs for the same source portfolio.  Tracks the
                  live frontier of the AI's best guess.

Price source policy
-------------------
All price lookups use AgentCache (technical agent) — never live yfinance
calls.  This means paper valuations stay within the project's existing cache
TTL (15 min for technical data) and never block the daily scheduler with
network I/O.

Fallback chain (per holding):
  1. AgentCache current_price / price / close   (live)
  2. inception_price stored at shadow creation   (frozen)
  3. Skip holding entirely (warn + exclude)      (never zero)

NAV floor guard
---------------
If the total paper NAV collapses to < 1.0 despite inception_value > 0
(all prices temporarily missing), the engine falls back to:
  - Last non-zero ShadowPortfolioSnapshot.total_value
  - Otherwise inception_value itself

This prevents fake -100% inception returns while prices are unavailable.

Price-frozen holdings
---------------------
When a shadow is created and no AgentCache price is available for a symbol,
_resolve_shares_from_weights stores:
    shares = market_value_dollars, inception_price = 1.0, price_frozen = True

In _compute_paper_value, price_frozen=True holdings ALWAYS use inception_price
(1.0), regardless of what AgentCache later contains.  Without this guard,
market_value_dollars × real_price inflates NAV by 100-300×.

Backward-compat: for DB rows written before this patch, holdings with
inception_price == 1.0 and shares > 1000 are inferred as price_frozen.

Paper cash accounting (correctness fix, 2026-07-07)
----------------------------------------------------
Target weights intentionally sum to less than 100% — the optimizer's own
cash floor (OPTIMIZER_PHILOSOPHY.md §2 Priority 7 "Idle-Cash Efficiency";
policy_engine.py's min_cash_pct enforcement). _resolve_shares_from_weights
now returns (holdings, cash) instead of holdings alone: cash is the
unallocated residual, (100 - sum(target_weight)) / 100 * total_portfolio_
value. Every caller persists it to ShadowPortfolio.paper_cash_balance and
carries it into the next rebalance's NAV basis. Previously this residual
was computed nowhere and stored nowhere — deleted from NAV at every
rebalance, compounding multiplicatively. assert_nav_conserved() is the
regression gate: every rebalance/creation site asserts equity + cash ==
the NAV it was derived from, and raises NavInvariantError (loud failure,
never silent) if not. See docs/DECISION_LOG.md, "Paper Portfolio Cash-Leak
Fix," for the full analysis. Historical ShadowPortfolioSnapshot rows are
NOT regenerated by this fix — only future rebalances stop leaking.

create_recommendation_shadow(db, snapshot_id, workspace_id) → dict
  AI Evaluation M1 (P2): a THIRD use of shadow_type="STATIC_FROZEN", keyed to
  the recommendation itself rather than to a human decision — see docstring
  on the function below for how it differs from create_static_frozen_shadow.

Historical regeneration + replay validation (Accounting Correctness Milestone 2,
2026-07-07)
----------------------------------------------------------------------------
Milestone 1 fixed the shared replay functions so *future* rebalances stop
leaking cash, but explicitly did not touch already-persisted
ShadowPortfolioSnapshot rows or ShadowPortfolio.paper_cash_balance values
written before the fix (docs/DECISION_LOG.md, "Paper Portfolio Cash-Leak
Fix"). Milestone 2 adds the regeneration engine that re-derives those
derived rows through the now-correct engine, plus a reusable determinism
check any future simulation engine can reuse:

  verify_deterministic_replay(fn, *args, **kwargs) — calls a pure replay
      function twice and deep-compares the results within tolerance; raises
      ReplayNonDeterministicError (loud, never silent) on divergence.

  regenerate_static_shadow(db, shadow_id) — re-derives (holdings, cash) for
      one STATIC_FROZEN or recommendation-keyed shadow from its ORIGINAL
      allocation source (never re-normalized, never re-decided) and replays
      its snapshot history via the existing _rebuild_shadow_snapshots.

  regenerate_active_model_shadow(db, portfolio_id) — ACTIVE_MODEL holdings
      change at every optimizer rebalance, so its history cannot be replayed
      from one fixed holdings set (this is why repair_shadow_portfolios has
      always skipped it — see that function's docstring). This function
      walks every RecommendationSnapshot from the shadow's immutable
      inception_date forward, exactly mirroring create_active_model_shadow's
      rebalance mechanic and ideal_series.py's day-by-day replay shape, and
      persists one ShadowPortfolioSnapshot per day.

  regenerate_portfolio_paper_history(db, portfolio_id, workspace_id) —
      orchestrates both of the above for one portfolio, then leaves
      AttributionMetric refresh to the caller (compute_portfolio_attribution
      is idempotent per day and reads shadow snapshots fresh — no separate
      regeneration step is meaningful for it, since it is a rolling
      trailing-window figure keyed to "today," not a historical series).

None of this touches RecommendationSnapshot, PortfolioSnapshot, PortfolioItem,
Transaction, or UserExecutionDecision — only ShadowPortfolio /
ShadowPortfolioSnapshot rows are rewritten, and shadow.inception_date /
shadow.inception_value are never touched (identity-preserving, values-only).

Public API
----------
value_shadow_portfolio(db, shadow_id) → dict
create_static_frozen_shadow(db, execution_decision_id, workspace_id) → dict
create_active_model_shadow(db, portfolio_id, snapshot_id, workspace_id) → dict
create_recommendation_shadow(db, snapshot_id, workspace_id) → dict
value_all_active_shadows(db, workspace_id) → list[dict]
repair_shadow_portfolios(db, workspace_id) → list[dict]
reset_active_model_inception(db, workspace_id) → list[dict]
verify_deterministic_replay(replay_fn, *args, **kwargs) → dict
regenerate_static_shadow(db, shadow_id) → dict
regenerate_active_model_shadow(db, portfolio_id) → dict
regenerate_portfolio_paper_history(db, portfolio_id, workspace_id) → dict
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, date, timedelta
from typing import Any

from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

_BENCHMARK_SYMBOL = "^GSPC"


# ─── DB-only price helpers ────────────────────────────────────────────────────

def _fetch_snapshot_prices(
    db: Session,
    symbols: list[str],
    on_or_before: str | None = None,
) -> dict[str, float]:
    """Return {symbol: price} from PortfolioSnapshot.holdings_json valuations.

    Portfolio snapshots store per-holding "current_price" written daily at
    17:45 ICT from live yfinance — the most reliable DB-only price source.
    Scans snapshot rows newest-first and keeps the first price seen per
    symbol, so each symbol resolves to its most recent available valuation.
    """
    from models.database import PortfolioSnapshot

    prices: dict[str, float] = {}
    if not symbols:
        return prices
    wanted = set(symbols)

    q = db.query(PortfolioSnapshot.snapshot_date, PortfolioSnapshot.holdings_json).filter(
        PortfolioSnapshot.holdings_json.isnot(None)
    )
    if on_or_before:
        q = q.filter(PortfolioSnapshot.snapshot_date <= on_or_before)
    rows = q.order_by(PortfolioSnapshot.snapshot_date.desc()).limit(200).all()

    for _, holdings_json in rows:
        if not (wanted - prices.keys()):
            break
        try:
            holdings = json.loads(holdings_json)
        except Exception:
            continue
        for h in holdings:
            sym = h.get("symbol")
            price = h.get("current_price")
            if sym in wanted and sym not in prices and price and float(price) > 0:
                prices[sym] = float(price)

    return prices


def _fetch_cached_prices(db: Session, symbols: list[str]) -> dict[str, float]:
    """Return {symbol: latest_price} from DB only — no yfinance calls.

    Source priority per symbol:
      1. AgentCache.technical result_json (current_price / price / close)
      2. PortfolioSnapshot.holdings_json valuation prices (daily close)

    Source 2 matters: the technical agent does not currently store any price
    key in its cache JSON, so without the snapshot fallback every shadow
    holding froze at inception_price and daily_return_pct stayed 0.0 forever.
    """
    from models.database import AgentCache

    prices: dict[str, float] = {}
    if not symbols:
        return prices

    rows = (
        db.query(AgentCache)
        .filter(AgentCache.symbol.in_(symbols), AgentCache.agent == "technical")
        .all()
    )
    for row in rows:
        if not row.result_json:
            continue
        try:
            data = json.loads(row.result_json)
            price = (
                data.get("current_price")
                or data.get("price")
                or data.get("close")
            )
            if price and isinstance(price, (int, float)) and float(price) > 0:
                prices[row.symbol] = float(price)
        except Exception:
            pass

    # Fallback: resolve remaining symbols from daily portfolio snapshot prices
    missing = [s for s in symbols if s not in prices]
    if missing:
        snapshot_prices = _fetch_snapshot_prices(db, missing)
        if snapshot_prices:
            logger.info(
                "[SHADOW] %d/%d prices resolved from portfolio snapshots (AgentCache miss)",
                len(snapshot_prices), len(missing),
            )
        prices.update(snapshot_prices)

    return prices


def _get_last_valid_nav(db: Session, shadow_id: int) -> float | None:
    """Return the most recent positive total_value from ShadowPortfolioSnapshot."""
    from models.database import ShadowPortfolioSnapshot

    row = (
        db.query(ShadowPortfolioSnapshot)
        .filter(
            ShadowPortfolioSnapshot.shadow_portfolio_id == shadow_id,
            ShadowPortfolioSnapshot.total_value > 0,
        )
        .order_by(ShadowPortfolioSnapshot.snapshot_date.desc())
        .first()
    )
    return float(row.total_value) if row else None


class NavInvariantError(RuntimeError):
    """Raised when a paper-portfolio engine's equity + cash does not
    reconcile against the NAV it was derived from — see assert_nav_conserved.
    """


def assert_nav_conserved(
    *,
    label: str,
    expected_nav: float,
    equity: float,
    cash: float,
    tolerance: float = 0.01,
) -> None:
    """Fail loudly if equity + cash does not equal expected_nav.

    Every paper-portfolio engine (Ideal Portfolio replay, ACTIVE_MODEL /
    STATIC_FROZEN shadow creation and rebalances) must call this immediately
    after resolving new holdings + cash from a target NAV, passing the
    identical price observations used for that resolution. This is the
    regression gate for the paper-portfolio cash-leak defect (see
    docs/DECISION_LOG.md, "Paper Portfolio Cash-Leak Fix"): a violation means
    value was created or destroyed during replay, which must never pass
    silently (ENGINEERING_PRINCIPLES.md "Failure Handling" — degraded modes
    must be observable, never silent).

    Reusable by any future paper-portfolio engine — this is the one place
    the invariant is checked; do not re-implement it elsewhere.
    """
    actual = equity + cash
    diff = abs(actual - expected_nav)
    tol = max(tolerance, abs(expected_nav) * 1e-6)
    if diff > tol:
        logger.error(
            "[NAV INVARIANT VIOLATED] %s: expected_nav=%.6f equity=%.6f cash=%.6f "
            "actual=%.6f diff=%.6f (tolerance=%.6f)",
            label, expected_nav, equity, cash, actual, diff, tol,
        )
        raise NavInvariantError(
            f"{label}: NAV not conserved — expected {expected_nav:.6f}, got "
            f"equity {equity:.6f} + cash {cash:.6f} = {actual:.6f} "
            f"(diff {diff:.6f} > tolerance {tol:.6f})"
        )


class ReplayNonDeterministicError(RuntimeError):
    """Raised when the same replay function, called twice with identical
    inputs, produced different results — see verify_deterministic_replay.
    """


def _deep_diff(a: Any, b: Any, path: str, tolerance: float) -> list[str]:
    """Recursively compare two JSON-like structures; return mismatch descriptions.

    Numeric leaves (including ints compared against floats) are compared
    within *tolerance* (absolute, or relative for large magnitudes); every
    other leaf type uses strict equality. Used only by
    verify_deterministic_replay below.
    """
    if isinstance(a, (int, float)) and isinstance(b, (int, float)) and not isinstance(a, bool) and not isinstance(b, bool):
        af, bf = float(a), float(b)
        if abs(af - bf) > max(tolerance, abs(af) * 1e-9):
            return [f"{path}: {af!r} != {bf!r} (diff {abs(af - bf):.8f})"]
        return []
    if isinstance(a, dict) and isinstance(b, dict):
        diffs: list[str] = []
        for k in sorted(set(a) | set(b), key=str):
            if k not in a:
                diffs.append(f"{path}.{k}: missing in first result")
            elif k not in b:
                diffs.append(f"{path}.{k}: missing in second result")
            else:
                diffs.extend(_deep_diff(a[k], b[k], f"{path}.{k}", tolerance))
        return diffs
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        if len(a) != len(b):
            return [f"{path}: length mismatch {len(a)} != {len(b)}"]
        diffs = []
        for i, (x, y) in enumerate(zip(a, b)):
            diffs.extend(_deep_diff(x, y, f"{path}[{i}]", tolerance))
        return diffs
    if a != b:
        return [f"{path}: {a!r} != {b!r}"]
    return []


def verify_deterministic_replay(replay_fn, *args, tolerance: float = 1e-6, **kwargs) -> dict[str, Any]:
    """Call *replay_fn* twice with identical arguments and assert the results
    match within *tolerance* — the reusable regression gate for AI Evaluation
    Accounting Correctness Milestone 2's determinism requirement ("given the
    same RecommendationSnapshots, PortfolioSnapshots, prices, and
    configuration, multiple replays must produce identical holdings/cash/
    NAV/return series").

    *replay_fn* MUST be pure and read-only (no DB writes) — calling it twice
    must have no side effects, or this check is meaningless.
    compute_ideal_series, compute_three_portfolios, and this module's
    _replay_active_model_series all satisfy that contract.

    Raises ReplayNonDeterministicError (loud, never silent —
    ENGINEERING_PRINCIPLES.md "Failure Handling") listing every diverging
    field on mismatch. Reusable by any future simulation engine — this is
    the one place replay determinism is checked; do not re-implement it
    elsewhere.
    """
    result1 = replay_fn(*args, **kwargs)
    result2 = replay_fn(*args, **kwargs)
    diffs = _deep_diff(result1, result2, "result", tolerance)
    if diffs:
        logger.error(
            "[REPLAY NON-DETERMINISTIC] %s: %d diverging field(s): %s",
            getattr(replay_fn, "__name__", repr(replay_fn)), len(diffs), diffs[:10],
        )
        raise ReplayNonDeterministicError(
            f"{getattr(replay_fn, '__name__', replay_fn)} produced different results "
            f"on repeated calls with identical inputs: {diffs[:10]}"
        )
    return {"deterministic": True, "result": result1}


def _resolve_shares_from_weights(
    allocations: list[dict],
    total_portfolio_value: float,
    prices: dict[str, float],
) -> tuple[list[dict], float]:
    """Convert target_weight_pct allocations into share counts, plus cash.

    For each allocation:
      market_value = target_weight / 100 * total_portfolio_value
      shares = market_value / inception_price   (if price available)

      If no price is available, stores:
        shares = market_value, inception_price = 1.0, price_frozen = True

      price_frozen=True marks the holding as a "dollar-value" entry whose
      contribution must NOT be re-multiplied by a future live price.

    Target weights summing to less than 100% is expected, not an error —
    it is the optimizer's own cash floor (OPTIMIZER_PHILOSOPHY.md §2
    Priority 7 "Idle-Cash Efficiency"; policy_engine.py's min_cash_pct
    enforcement). The unallocated remainder is real paper cash and must
    never be silently discarded:

        cash = (100 - sum(target_weight)) / 100 * total_portfolio_value

    Returns (holdings, cash). Callers MUST carry `cash` forward — persisted
    as ShadowPortfolio.paper_cash_balance for the shadow engines, or as an
    in-memory accumulator for the stateless Ideal replay — and add it back
    into the NAV basis of the next rebalance. Dropping it reproduces the
    cash-leak defect this function was fixed to eliminate (see
    docs/DECISION_LOG.md, "Paper Portfolio Cash-Leak Fix").
    """
    holdings: list[dict] = []
    deployed_weight = 0.0
    for a in allocations:
        sym = a.get("symbol")
        if not sym:
            continue
        target_weight = float(a.get("target_weight") or 0)
        deployed_weight += target_weight
        market_value = target_weight / 100.0 * total_portfolio_value
        inception_price = prices.get(sym)

        if inception_price and inception_price > 0:
            shares = round(market_value / inception_price, 6)
            price_frozen = False
        else:
            # No price: freeze market_value as "shares at price 1"
            shares = round(market_value, 6)
            inception_price = 1.0
            price_frozen = True

        holdings.append({
            "symbol": sym,
            "target_weight_pct": target_weight,
            "action": a.get("action"),
            "shares": shares,
            "inception_price": inception_price,
            "price_frozen": price_frozen,
        })

    if deployed_weight > 100.0001:
        logger.warning(
            "[SHADOW] target_weight sum %.4f%% exceeds 100%% — clamping cash "
            "residual to 0 (over-allocation should already be prevented "
            "upstream by the optimizer/policy engine)",
            deployed_weight,
        )
    cash = max(0.0, (100.0 - deployed_weight) / 100.0 * total_portfolio_value)
    return holdings, cash


# ─── Paper valuation ──────────────────────────────────────────────────────────

def _compute_paper_value(
    holdings: list[dict],
    prices: dict[str, float],
) -> tuple[float, list[dict]]:
    """Compute total paper value from inception holdings + cached prices.

    Valuation priority per holding:
      1. shares × cached_current_price   (price_frozen=False, cache hit)
      2. shares × inception_price        (price_frozen=True OR cache miss)
      Skip                               (shares ≤ 0, and no valid price at all)

    NEVER multiplies dollar-value "shares" (price_frozen=True) by a live price.
    This prevents 100-300× NAV inflation when prices become cached after creation.

    Backward-compat rule: holdings with inception_price == 1.0 and shares > 1000
    are treated as price_frozen even if the flag is absent (old DB rows).
    """
    total = 0.0
    enriched: list[dict] = []

    for h in holdings:
        sym = h.get("symbol", "")
        shares = float(h.get("shares") or 0)
        inception_price = float(h.get("inception_price") or 0)
        price_frozen = h.get("price_frozen", False)

        # Backward-compat: infer price_frozen for old DB rows
        if not price_frozen and inception_price == 1.0 and shares > 1000:
            price_frozen = True

        if shares <= 0:
            enriched.append({**h, "current_price": inception_price, "market_value": 0.0, "price_source": "zero_shares"})
            continue

        if price_frozen:
            # Dollar-value holding: always frozen at inception_price (1.0)
            current_price = inception_price if inception_price > 0 else 1.0
            price_source = "inception_frozen"
        else:
            cached = prices.get(sym)
            if cached and cached > 0:
                current_price = cached
                price_source = "cached"
            elif inception_price > 0:
                current_price = inception_price
                price_source = "inception_fallback"
            else:
                # No valid price — exclude holding, log warning
                logger.warning(
                    "[SHADOW] No price for %s (shares=%.4f) — excluded from valuation",
                    sym, shares,
                )
                enriched.append({**h, "current_price": None, "market_value": None, "price_source": "missing"})
                continue

        mv = shares * current_price
        total += mv
        enriched.append({
            **h,
            "current_price": current_price,
            "inception_price": inception_price,
            "market_value": round(mv, 2),
            "price_source": price_source,
        })

    return total, enriched


def _benchmark_return_pct(
    db: Session,
    benchmark_symbol: str,
    inception_date: str,
    today_str: str,
) -> float | None:
    """Approximate benchmark return since inception using BenchmarkPrice table."""
    from models.database import BenchmarkPrice

    start = (
        db.query(BenchmarkPrice)
        .filter(BenchmarkPrice.symbol == benchmark_symbol, BenchmarkPrice.price_date >= inception_date)
        .order_by(BenchmarkPrice.price_date)
        .first()
    )
    end = (
        db.query(BenchmarkPrice)
        .filter(BenchmarkPrice.symbol == benchmark_symbol, BenchmarkPrice.price_date <= today_str)
        .order_by(BenchmarkPrice.price_date.desc())
        .first()
    )
    if start and end and start.close_price and end.close_price and start.close_price != 0:
        return round((end.close_price - start.close_price) / start.close_price * 100, 4)
    return None


# ─── Core valuation ──────────────────────────────────────────────────────────

def value_shadow_portfolio(db: Session, shadow_id: int) -> dict[str, Any]:
    """Price a shadow portfolio at cached market prices and write a snapshot row.

    NAV floor guard: if computed total_value < 1.0 and inception_value > 0,
    falls back to last valid snapshot NAV or inception_value to prevent
    fake -100% inception returns when prices are temporarily unavailable.

    Return sanity: inception_return_pct is set to None (not shown) when the
    raw computed value exceeds plausible bounds (< -99% or > +1000%).
    """
    from models.database import ShadowPortfolio, ShadowPortfolioSnapshot

    shadow = db.query(ShadowPortfolio).filter_by(id=shadow_id).first()
    if not shadow:
        return {"error": "shadow_portfolio_not_found", "id": shadow_id}

    today_str = date.today().isoformat()

    existing = (
        db.query(ShadowPortfolioSnapshot)
        .filter_by(shadow_portfolio_id=shadow_id, snapshot_date=today_str)
        .first()
    )

    holdings: list[dict] = []
    try:
        raw = shadow.inception_holdings_json
        if raw:
            holdings = json.loads(raw)
    except Exception:
        pass

    symbols = [h["symbol"] for h in holdings if h.get("symbol")]
    prices = _fetch_cached_prices(db, symbols)
    total_value, enriched = _compute_paper_value(holdings, prices)
    total_value += shadow.paper_cash_balance

    # ── NAV floor guard ────────────────────────────────────────────────────────
    # If total_value collapsed to near zero but we have an inception baseline,
    # use the last known valid NAV rather than reporting -100%.
    inception_value: float | None = shadow.inception_value
    if total_value < 1.0 and (inception_value or 0) > 0:
        last_nav = _get_last_valid_nav(db, shadow_id)
        if last_nav and last_nav > 0:
            total_value = last_nav
            logger.info(
                "[SHADOW] NAV fallback: shadow_id=%s using last valid snapshot %.2f",
                shadow_id, total_value,
            )
        else:
            total_value = inception_value  # type: ignore[assignment]
            logger.info(
                "[SHADOW] NAV fallback: shadow_id=%s using inception_value %.2f",
                shadow_id, total_value,
            )

    # ── Inception value backfill ───────────────────────────────────────────────
    # If inception_value was never set (e.g. total_portfolio_value was 0 at creation),
    # use the first valid total_value we compute.
    if (not inception_value or inception_value <= 0) and total_value > 0:
        inception_value = total_value
        shadow.inception_value = total_value
        logger.info(
            "[SHADOW] Backfilled inception_value=%.2f for shadow_id=%s",
            total_value, shadow_id,
        )

    # ── Inception return ───────────────────────────────────────────────────────
    inception_return_pct: float | None = None
    if inception_value and inception_value > 0 and total_value > 0:
        raw_return = (total_value - inception_value) / inception_value * 100
        # Sanity bounds: suppress clearly corrupted values rather than display -100%
        if -99.9 <= raw_return <= 1000.0:
            inception_return_pct = round(raw_return, 4)
        else:
            logger.warning(
                "[SHADOW] shadow_id=%s inception_return=%.2f%% out of plausible range — suppressed",
                shadow_id, raw_return,
            )

    benchmark_symbol = _BENCHMARK_SYMBOL
    benchmark_ret = _benchmark_return_pct(db, benchmark_symbol, shadow.inception_date, today_str)
    alpha = None
    if inception_return_pct is not None and benchmark_ret is not None:
        alpha = round(inception_return_pct - benchmark_ret, 4)

    # ── Daily return ───────────────────────────────────────────────────────────
    daily_return_pct: float | None = None
    prev = (
        db.query(ShadowPortfolioSnapshot)
        .filter(
            ShadowPortfolioSnapshot.shadow_portfolio_id == shadow_id,
            ShadowPortfolioSnapshot.snapshot_date < today_str,
            ShadowPortfolioSnapshot.total_value > 0,
        )
        .order_by(ShadowPortfolioSnapshot.snapshot_date.desc())
        .first()
    )
    if prev and prev.total_value and prev.total_value > 0 and total_value > 0:
        raw_daily = (total_value - prev.total_value) / prev.total_value * 100
        if -50.0 <= raw_daily <= 50.0:
            daily_return_pct = round(raw_daily, 4)

    try:
        if existing:
            existing.total_value = total_value
            existing.return_pct_since_inception = inception_return_pct
            existing.daily_return_pct = daily_return_pct
            existing.holdings_json = json.dumps(enriched, default=str)
            existing.benchmark_symbol = benchmark_symbol
            existing.benchmark_return_pct = benchmark_ret
            existing.alpha = alpha
            existing.recommendation_snapshot_id = shadow.recommendation_snapshot_id
        else:
            snap = ShadowPortfolioSnapshot(
                shadow_portfolio_id=shadow_id,
                snapshot_date=today_str,
                total_value=total_value,
                return_pct_since_inception=inception_return_pct,
                daily_return_pct=daily_return_pct,
                holdings_json=json.dumps(enriched, default=str),
                benchmark_symbol=benchmark_symbol,
                benchmark_return_pct=benchmark_ret,
                alpha=alpha,
                recommendation_snapshot_id=shadow.recommendation_snapshot_id,
                created_at=datetime.utcnow(),
            )
            db.add(snap)

        shadow.current_value = total_value
        shadow.inception_return_pct = inception_return_pct
        shadow.last_valued_at = datetime.utcnow()
        db.commit()

    except Exception as exc:
        logger.warning("[SHADOW] snapshot write failed for shadow_id=%s: %s", shadow_id, exc)
        db.rollback()

    holdings_priced = len([h for h in enriched if h.get("price_source") in ("cached", "inception_fallback")])
    holdings_frozen = len([h for h in enriched if h.get("price_source") == "inception_frozen"])
    holdings_missing = len([h for h in enriched if h.get("price_source") == "missing"])

    return {
        "shadow_id": shadow_id,
        "shadow_type": shadow.shadow_type,
        "snapshot_date": today_str,
        "total_value": total_value,
        "inception_return_pct": inception_return_pct,
        "daily_return_pct": daily_return_pct,
        "alpha": alpha,
        "benchmark_symbol": benchmark_symbol,
        "benchmark_return_pct": benchmark_ret,
        "holdings_priced": holdings_priced,
        "holdings_frozen": holdings_frozen,
        "holdings_missing": holdings_missing,
        "holdings_total": len(holdings),
    }


def value_all_active_shadows(db: Session, workspace_id: int) -> list[dict]:
    """Value every active shadow portfolio for the workspace (for the daily job)."""
    from models.database import ShadowPortfolio

    shadows = (
        db.query(ShadowPortfolio)
        .filter_by(workspace_id=workspace_id, is_active=True)
        .all()
    )
    results = []
    for s in shadows:
        try:
            results.append(value_shadow_portfolio(db, s.id))
        except Exception as exc:
            logger.warning("[SHADOW] value_all_active_shadows: shadow_id=%s failed: %s", s.id, exc)
            results.append({"shadow_id": s.id, "error": str(exc)})
    return results


# ─── Factory helpers ──────────────────────────────────────────────────────────

def create_static_frozen_shadow(
    db: Session,
    execution_decision_id: int,
    workspace_id: int,
) -> dict[str, Any]:
    """Create a STATIC_FROZEN shadow from a UserExecutionDecision row.

    Holdings are resolved in this priority order:
      1. approved_allocations_json from the decision (APPROVED path)
      2. projected_allocations_json from the linked RecommendationSnapshot
      3. Actual PortfolioItem holdings (fallback when optimizer returned NO_ACTION)

    If total_portfolio_value is 0, falls back to actual portfolio market value
    computed from AgentCache prices × PortfolioItem.shares.

    Shares are computed from target_weight_pct × total_value ÷ price.
    When no price is cached, price_frozen=True marks the holding to prevent
    future price-scale corruption.
    """
    from models.database import (
        ShadowPortfolio, UserExecutionDecision, RecommendationSnapshot,
        PortfolioItem,
    )

    decision = db.query(UserExecutionDecision).filter_by(id=execution_decision_id).first()
    if not decision:
        return {"error": "decision_not_found"}

    snap = db.query(RecommendationSnapshot).filter_by(
        id=decision.recommendation_snapshot_id
    ).first()

    # Resolve allocations: prefer approved_allocations for APPROVED decisions
    allocs_raw = decision.approved_allocations_json or (
        snap.projected_allocations_json if snap else None
    )
    allocs: list[dict] = []
    if allocs_raw:
        try:
            allocs = json.loads(allocs_raw)
        except Exception:
            pass

    total_portfolio_value: float = (snap.total_portfolio_value if snap else None) or 0.0

    # Resolve prices early (shared by both allocation path and fallback path)
    alloc_symbols = [a.get("symbol") for a in allocs if a.get("symbol")]
    prices = _fetch_cached_prices(db, alloc_symbols) if alloc_symbols else {}

    # ── Fallback: use actual portfolio holdings when allocations are empty ─────
    if not allocs:
        portfolio_items = (
            db.query(PortfolioItem)
            .filter_by(portfolio_id=decision.portfolio_id)
            .all()
        )
        if portfolio_items:
            item_symbols = [i.symbol for i in portfolio_items]
            item_prices = _fetch_cached_prices(db, item_symbols)

            # Compute total market value for weight calculation
            items_mv: dict[str, float] = {}
            for item in portfolio_items:
                price = item_prices.get(item.symbol) or item.avg_cost or 0.0
                if price > 0 and item.shares and item.shares > 0:
                    items_mv[item.symbol] = price * item.shares

            total_items_value = sum(items_mv.values())

            if total_items_value > 0:
                if total_portfolio_value <= 0:
                    total_portfolio_value = total_items_value
                for item in portfolio_items:
                    mv = items_mv.get(item.symbol, 0)
                    weight = mv / total_portfolio_value * 100 if total_portfolio_value > 0 else 0
                    if weight > 0:
                        allocs.append({
                            "symbol": item.symbol,
                            "target_weight": weight,
                            "action": "HOLD",
                        })
                prices.update(item_prices)
                logger.info(
                    "[SHADOW] create_static_frozen: no optimizer allocations, "
                    "using %d actual portfolio items as baseline (total=%.2f)",
                    len(allocs), total_portfolio_value,
                )

    holdings, cash = _resolve_shares_from_weights(allocs, total_portfolio_value, prices)
    deployed_value, _ = _compute_paper_value(holdings, prices)
    assert_nav_conserved(
        label=f"create_static_frozen_shadow decision_id={execution_decision_id}",
        expected_nav=total_portfolio_value, equity=deployed_value, cash=cash,
    )

    inception_date = date.today().isoformat()

    shadow = ShadowPortfolio(
        workspace_id=workspace_id,
        portfolio_id=decision.portfolio_id,
        shadow_type="STATIC_FROZEN",
        name=f"Frozen @ {inception_date} ({decision.decision})",
        inception_date=inception_date,
        inception_value=total_portfolio_value if total_portfolio_value > 0 else None,
        recommendation_snapshot_id=decision.recommendation_snapshot_id,
        execution_decision_id=execution_decision_id,
        inception_holdings_json=json.dumps(holdings, default=str),
        paper_cash_balance=cash,
        is_active=True,
        created_at=datetime.utcnow(),
    )
    db.add(shadow)
    db.commit()
    db.refresh(shadow)

    holdings_priced = len([h for h in holdings if not h.get("price_frozen")])
    logger.info(
        "[SHADOW] Created STATIC_FROZEN id=%s for decision_id=%s "
        "(%d holdings, %d priced, %d frozen)",
        shadow.id, execution_decision_id, len(holdings),
        holdings_priced, len(holdings) - holdings_priced,
    )
    return {
        "shadow_id": shadow.id,
        "shadow_type": "STATIC_FROZEN",
        "inception_date": inception_date,
        "holdings_count": len(holdings),
        "holdings_priced": holdings_priced,
        "holdings_frozen": len(holdings) - holdings_priced,
    }


def create_active_model_shadow(
    db: Session,
    portfolio_id: int,
    snapshot_id: int,
    workspace_id: int,
) -> dict[str, Any]:
    """Create or refresh an ACTIVE_MODEL shadow from the latest optimizer snapshot.

    On refresh, computes the shadow's own running NAV from current holdings and
    prices before rebalancing — never resets inception_date or inception_value so
    the shadow accumulates a true cumulative track record across optimizer runs.

    Holdings with no cached price are marked price_frozen=True to prevent
    future NAV inflation when prices become available.
    """
    from models.database import ShadowPortfolio, RecommendationSnapshot

    snap = db.query(RecommendationSnapshot).filter_by(id=snapshot_id).first()
    if not snap:
        return {"error": "snapshot_not_found"}

    allocs: list[dict] = []
    if snap.projected_allocations_json:
        try:
            allocs = json.loads(snap.projected_allocations_json)
        except Exception:
            pass

    today_str = date.today().isoformat()
    symbols = [a.get("symbol") for a in allocs if a.get("symbol")]
    prices = _fetch_cached_prices(db, symbols)

    existing = (
        db.query(ShadowPortfolio)
        .filter_by(portfolio_id=portfolio_id, shadow_type="ACTIVE_MODEL", is_active=True)
        .order_by(ShadowPortfolio.created_at.desc())
        .first()
    )

    if existing:
        # Compute shadow's own running NAV from current holdings — never use actual
        # portfolio NAV, which would tether the shadow to deposits/withdrawals.
        old_holdings: list[dict] = []
        try:
            if existing.inception_holdings_json:
                old_holdings = json.loads(existing.inception_holdings_json)
        except Exception:
            pass

        if old_holdings:
            old_syms = [h["symbol"] for h in old_holdings if h.get("symbol")]
            old_prices = _fetch_cached_prices(db, old_syms)
            running_nav, _ = _compute_paper_value(old_holdings, old_prices)
            running_nav += existing.paper_cash_balance or 0.0
            if running_nav < 1.0:
                running_nav = (
                    _get_last_valid_nav(db, existing.id)
                    or existing.inception_value
                    or snap.total_portfolio_value
                    or 0.0
                )
        else:
            running_nav = (snap.total_portfolio_value or 0.0) + (existing.paper_cash_balance or 0.0)

        if running_nav <= 0:
            running_nav = snap.total_portfolio_value or 1.0

        new_holdings, new_cash = _resolve_shares_from_weights(allocs, running_nav, prices)
        deployed_value, _ = _compute_paper_value(new_holdings, prices)
        assert_nav_conserved(
            label=f"create_active_model_shadow rebalance shadow_id={existing.id}",
            expected_nav=running_nav, equity=deployed_value, cash=new_cash,
        )
        holdings_priced = len([h for h in new_holdings if not h.get("price_frozen")])

        # inception_date and inception_value are NEVER touched after first creation
        existing.recommendation_snapshot_id = snapshot_id
        existing.inception_holdings_json = json.dumps(new_holdings, default=str)
        existing.paper_cash_balance = new_cash
        db.commit()

        logger.info(
            "[SHADOW] Rebalanced ACTIVE_MODEL id=%s portfolio_id=%s "
            "running_nav=%.2f cash=%.2f → new weights (%d holdings, %d priced, %d frozen)",
            existing.id, portfolio_id, running_nav, new_cash,
            len(new_holdings), holdings_priced, len(new_holdings) - holdings_priced,
        )
        return {
            "shadow_id": existing.id,
            "shadow_type": "ACTIVE_MODEL",
            "action": "rebalanced",
            "running_nav": round(running_nav, 2),
            "holdings_count": len(new_holdings),
            "holdings_priced": holdings_priced,
            "holdings_frozen": len(new_holdings) - holdings_priced,
        }

    # First-time creation — use actual portfolio NAV as inception baseline
    total_portfolio_value = snap.total_portfolio_value or 0.0
    holdings, cash = _resolve_shares_from_weights(allocs, total_portfolio_value, prices)
    deployed_value, _ = _compute_paper_value(holdings, prices)
    assert_nav_conserved(
        label=f"create_active_model_shadow inception portfolio_id={portfolio_id}",
        expected_nav=total_portfolio_value, equity=deployed_value, cash=cash,
    )
    holdings_priced = len([h for h in holdings if not h.get("price_frozen")])

    shadow = ShadowPortfolio(
        workspace_id=workspace_id,
        portfolio_id=portfolio_id,
        shadow_type="ACTIVE_MODEL",
        name=f"Active Model Portfolio ({today_str})",
        inception_date=today_str,
        inception_value=total_portfolio_value if total_portfolio_value > 0 else None,
        recommendation_snapshot_id=snapshot_id,
        inception_holdings_json=json.dumps(holdings, default=str),
        paper_cash_balance=cash,
        is_active=True,
        created_at=datetime.utcnow(),
    )
    db.add(shadow)
    db.commit()
    db.refresh(shadow)
    logger.info(
        "[SHADOW] Created ACTIVE_MODEL id=%s for portfolio_id=%s "
        "(%d holdings, %d priced, %d frozen)",
        shadow.id, portfolio_id, len(holdings),
        holdings_priced, len(holdings) - holdings_priced,
    )
    return {
        "shadow_id": shadow.id,
        "shadow_type": "ACTIVE_MODEL",
        "action": "created",
        "holdings_count": len(holdings),
        "holdings_priced": holdings_priced,
        "holdings_frozen": len(holdings) - holdings_priced,
    }


# ─── Recommendation-keyed counterfactual (AI Evaluation M1, P2) ──────────────

def create_recommendation_shadow(
    db: Session,
    snapshot_id: int,
    workspace_id: int,
) -> dict[str, Any]:
    """Create the recommendation-keyed STATIC_FROZEN shadow for one snapshot.

    Differs from create_static_frozen_shadow: that function freezes holdings at
    the moment a UserExecutionDecision was *recorded* (execution_decision_id
    set). This one freezes holdings at the moment the recommendation was
    *made* (execution_decision_id stays NULL) — every optimizer run gets a
    counterfactual return series from day 0, regardless of whether the human
    ever approves, rejects, or ignores it. This is what the Horizon Grading
    Engine (services/evaluation/horizon_grader.py) reads to grade
    recommendation quality independent of execution behavior (PHILOSOPHY §11).

    Idempotent: one shadow per snapshot_id — returns the existing shadow
    (action="exists") on a repeat call rather than creating a duplicate.

    Backfill path: when snapshot.created_at is not today (the CLI backfill
    command, run against historical snapshots), also replays the shadow's
    full daily valuation history from PortfolioSnapshot prices so its mature
    horizons are immediately gradable — reusing the exact replay routine
    already used by repair_shadow_portfolios (_snapshot_price_history /
    _rebuild_shadow_snapshots) rather than re-deriving valuation math.
    """
    from models.database import ShadowPortfolio, RecommendationSnapshot

    existing = (
        db.query(ShadowPortfolio)
        .filter_by(
            recommendation_snapshot_id=snapshot_id,
            shadow_type="STATIC_FROZEN",
            execution_decision_id=None,
        )
        .first()
    )
    if existing:
        return {"shadow_id": existing.id, "action": "exists"}

    snap = db.query(RecommendationSnapshot).filter_by(id=snapshot_id).first()
    if not snap:
        return {"error": "snapshot_not_found", "snapshot_id": snapshot_id}

    allocs: list[dict] = []
    if snap.projected_allocations_json:
        try:
            allocs = json.loads(snap.projected_allocations_json)
        except Exception:
            pass
    if not allocs:
        return {"error": "no_allocations", "snapshot_id": snapshot_id}

    inception_date = (
        snap.created_at.date().isoformat() if snap.created_at else date.today().isoformat()
    )
    total_portfolio_value = snap.total_portfolio_value or 0.0

    symbols = [a.get("symbol") for a in allocs if a.get("symbol")]
    prices = _fetch_snapshot_prices(db, symbols, on_or_before=inception_date)
    missing = [s for s in symbols if s not in prices]
    if missing:
        prices.update(_fetch_cached_prices(db, missing))

    holdings, cash = _resolve_shares_from_weights(allocs, total_portfolio_value, prices)
    deployed_value, _ = _compute_paper_value(holdings, prices)
    assert_nav_conserved(
        label=f"create_recommendation_shadow snapshot_id={snapshot_id}",
        expected_nav=total_portfolio_value, equity=deployed_value, cash=cash,
    )

    shadow = ShadowPortfolio(
        workspace_id=workspace_id,
        portfolio_id=snap.portfolio_id,
        shadow_type="STATIC_FROZEN",
        name=f"Recommendation @ {inception_date} (snapshot {snapshot_id})",
        inception_date=inception_date,
        inception_value=total_portfolio_value if total_portfolio_value > 0 else None,
        recommendation_snapshot_id=snapshot_id,
        execution_decision_id=None,
        inception_holdings_json=json.dumps(holdings, default=str),
        paper_cash_balance=cash,
        is_active=True,
        created_at=datetime.utcnow(),
    )
    db.add(shadow)
    db.commit()
    db.refresh(shadow)

    backfilled = 0
    if inception_date < date.today().isoformat():
        history = _snapshot_price_history(db)
        if history:
            backfilled = _rebuild_shadow_snapshots(db, shadow, holdings, history)
            db.commit()

    logger.info(
        "[SHADOW] Created recommendation shadow id=%s for snapshot_id=%s "
        "(%d holdings, %d backfilled snapshots)",
        shadow.id, snapshot_id, len(holdings), backfilled,
    )
    return {
        "shadow_id": shadow.id,
        "action": "created",
        "holdings_count": len(holdings),
        "backfilled_snapshots": backfilled,
    }


# ─── One-time repair (price_frozen holdings + flat snapshot history) ─────────

def _snapshot_price_history(db: Session) -> dict[str, dict[str, float]]:
    """Return {snapshot_date: {symbol: price}} from all PortfolioSnapshot rows."""
    from models.database import PortfolioSnapshot

    history: dict[str, dict[str, float]] = {}
    rows = (
        db.query(PortfolioSnapshot.snapshot_date, PortfolioSnapshot.holdings_json)
        .filter(PortfolioSnapshot.holdings_json.isnot(None))
        .order_by(PortfolioSnapshot.snapshot_date.asc())
        .all()
    )
    for snap_date, holdings_json in rows:
        try:
            holdings = json.loads(holdings_json)
        except Exception:
            continue
        day = history.setdefault(snap_date, {})
        for h in holdings:
            sym = h.get("symbol")
            price = h.get("current_price")
            if sym and price and float(price) > 0:
                day[sym] = float(price)
    return history


def _price_near_date(
    history: dict[str, dict[str, float]],
    date_str: str,
    symbol: str,
) -> float | None:
    """Price for *symbol* on the nearest date ≤ date_str, else first date after."""
    best: float | None = None
    for d in sorted(history):
        p = history[d].get(symbol)
        if p is None:
            continue
        if d <= date_str:
            best = p          # keep walking forward to the latest date ≤ target
        elif best is None:
            return p          # no observation before target — use first after
        else:
            break
    return best


def _rebuild_shadow_snapshots(
    db: Session,
    shadow: Any,
    holdings: list[dict],
    history: dict[str, dict[str, float]],
) -> int:
    """Re-derive every ShadowPortfolioSnapshot from daily snapshot prices (LOCF).

    Walks all price-history dates in order, carrying prices forward, and
    upserts one snapshot per date ≥ inception_date. Returns rows written.
    """
    from models.database import ShadowPortfolioSnapshot

    existing_rows = {
        s.snapshot_date: s
        for s in db.query(ShadowPortfolioSnapshot)
        .filter(ShadowPortfolioSnapshot.shadow_portfolio_id == shadow.id)
        .all()
    }
    # Union of price dates and already-written snapshot dates ≥ inception
    rebuild_dates = sorted(
        {d for d in history if d >= shadow.inception_date}
        | {d for d in existing_rows if d >= shadow.inception_date}
    )

    last_prices: dict[str, float] = {}
    # Seed LOCF with prices observed on/before inception
    for d in sorted(history):
        if d > shadow.inception_date:
            break
        last_prices.update(history[d])

    inception_value: float | None = shadow.inception_value
    prev_total: float | None = None
    written = 0

    for d in rebuild_dates:
        if d in history:
            last_prices.update(history[d])

        total, _ = _compute_paper_value(holdings, last_prices)
        total += shadow.paper_cash_balance or 0.0
        if total <= 0:
            continue

        if not inception_value or inception_value <= 0:
            inception_value = total
            shadow.inception_value = total

        inception_ret: float | None = None
        raw_ret = (total - inception_value) / inception_value * 100
        if -99.9 <= raw_ret <= 1000.0:
            inception_ret = round(raw_ret, 4)

        daily_ret: float | None = None
        if prev_total and prev_total > 0:
            raw_daily = (total - prev_total) / prev_total * 100
            if -50.0 <= raw_daily <= 50.0:
                daily_ret = round(raw_daily, 4)
        prev_total = total

        snap = existing_rows.get(d)
        if snap:
            snap.total_value = total
            snap.return_pct_since_inception = inception_ret
            snap.daily_return_pct = daily_ret
        else:
            db.add(ShadowPortfolioSnapshot(
                shadow_portfolio_id=shadow.id,
                snapshot_date=d,
                total_value=total,
                return_pct_since_inception=inception_ret,
                daily_return_pct=daily_ret,
                holdings_json=None,
                benchmark_symbol=_BENCHMARK_SYMBOL,
                created_at=datetime.utcnow(),
            ))
        written += 1

        shadow.current_value = total
        shadow.inception_return_pct = inception_ret

    return written


def repair_shadow_portfolios(db: Session, workspace_id: int) -> list[dict[str, Any]]:
    """One-time repair for shadows created while no DB price source resolved.

    Fixes two historical defects (root cause: AgentCache.technical rows carry
    no price keys, so _fetch_cached_prices returned {} at creation AND at
    every daily valuation — all holdings froze at inception_price=1.0 and
    daily_return_pct stayed 0.0 forever):

      1. price_frozen dollar-value holdings → converted to real share counts
         using the PortfolioSnapshot price nearest the shadow's inception date.
      2. Empty inception_holdings_json (pre-fallback rows) → rebuilt from the
         linked decision's approved allocations or the recommendation
         snapshot's projected allocations.

    Then re-derives the full ShadowPortfolioSnapshot history from daily
    portfolio snapshot prices so shadow returns reflect real market moves.
    """
    from models.database import (
        ShadowPortfolio, UserExecutionDecision, RecommendationSnapshot,
    )

    history = _snapshot_price_history(db)
    if not history:
        return [{"status": "no_price_history"}]

    shadows = (
        db.query(ShadowPortfolio)
        .filter_by(workspace_id=workspace_id, is_active=True)
        .order_by(ShadowPortfolio.id)
        .all()
    )

    results: list[dict[str, Any]] = []
    for shadow in shadows:
        result: dict[str, Any] = {"shadow_id": shadow.id, "shadow_type": shadow.shadow_type}
        try:
            holdings: list[dict] = []
            if shadow.inception_holdings_json:
                try:
                    holdings = json.loads(shadow.inception_holdings_json)
                except Exception:
                    holdings = []

            # ── Rebuild empty holdings from linked allocations ────────────────
            if not holdings:
                decision = (
                    db.query(UserExecutionDecision).filter_by(id=shadow.execution_decision_id).first()
                    if shadow.execution_decision_id else None
                )
                snap = (
                    db.query(RecommendationSnapshot).filter_by(id=shadow.recommendation_snapshot_id).first()
                    if shadow.recommendation_snapshot_id else None
                )
                allocs_raw = (decision.approved_allocations_json if decision else None) or (
                    snap.projected_allocations_json if snap else None
                )
                allocs: list[dict] = []
                if allocs_raw:
                    try:
                        allocs = json.loads(allocs_raw)
                    except Exception:
                        pass
                total_value = shadow.inception_value or (
                    (snap.total_portfolio_value if snap else None) or 0.0
                )
                if not allocs or total_value <= 0:
                    result.update(status="skipped_no_allocations", holdings=0)
                    results.append(result)
                    continue
                for a in allocs:
                    sym = a.get("symbol")
                    if not sym:
                        continue
                    weight = float(a.get("target_weight") or 0)
                    holdings.append({
                        "symbol": sym,
                        "target_weight_pct": weight,
                        "action": a.get("action"),
                        "shares": round(weight / 100.0 * total_value, 6),
                        "inception_price": 1.0,
                        "price_frozen": True,  # un-frozen below with real prices
                    })
                result["holdings_rebuilt"] = True

            # ── Un-freeze dollar-value holdings with inception-date prices ────
            unfrozen = 0
            still_frozen = 0
            for h in holdings:
                frozen = h.get("price_frozen", False)
                # Backward-compat inference (same rule as _compute_paper_value)
                if not frozen and float(h.get("inception_price") or 0) == 1.0 and float(h.get("shares") or 0) > 1000:
                    frozen = True
                if not frozen:
                    continue
                price = _price_near_date(history, shadow.inception_date, h.get("symbol", ""))
                if price and price > 0:
                    dollars = float(h.get("shares") or 0)
                    h["shares"] = round(dollars / price, 6)
                    h["inception_price"] = price
                    h["price_frozen"] = False
                    unfrozen += 1
                else:
                    still_frozen += 1

            shadow.inception_holdings_json = json.dumps(holdings, default=str)

            # ── Skip full snapshot rebuild for ACTIVE_MODEL ──────────────────
            # ACTIVE_MODEL allocation changes at each optimizer run; replaying its
            # full SPS history from a single static holdings set produces wrong values.
            # Holdings are still un-frozen above to keep running_nav accurate.
            if shadow.shadow_type == "ACTIVE_MODEL":
                db.commit()
                result.update(
                    status="unfrozen_holdings_only",
                    holdings=len(holdings),
                    unfrozen=unfrozen,
                    still_frozen=still_frozen,
                    snapshots_rebuilt=0,
                )
                logger.info(
                    "[SHADOW] Repair skipped snapshot rebuild for ACTIVE_MODEL shadow_id=%s "
                    "(%d holdings, %d unfrozen)",
                    shadow.id, len(holdings), unfrozen,
                )
                results.append(result)
                continue

            # ── Rebuild snapshot history with real daily prices ───────────────
            rows = _rebuild_shadow_snapshots(db, shadow, holdings, history)
            db.commit()

            result.update(
                status="repaired",
                holdings=len(holdings),
                unfrozen=unfrozen,
                still_frozen=still_frozen,
                snapshots_rebuilt=rows,
                inception_return_pct=shadow.inception_return_pct,
            )
            logger.info(
                "[SHADOW] Repaired shadow_id=%s: %d holdings (%d unfrozen), %d snapshots rebuilt",
                shadow.id, len(holdings), unfrozen, rows,
            )
        except Exception as exc:
            db.rollback()
            logger.error("[SHADOW] Repair failed for shadow_id=%s: %s", shadow.id, exc)
            result.update(status="error", error=str(exc))
        results.append(result)

    return results


def reset_active_model_inception(db: Session, workspace_id: int) -> list[dict[str, Any]]:
    """Reset ACTIVE_MODEL shadow inception to today's date and current NAV.

    Clears all ShadowPortfolioSnapshot history for each ACTIVE_MODEL shadow
    and resets inception_date/inception_value so the cumulative track record
    starts fresh from the current point in time.

    Call once after deploying the Option B rebalancing fix to clear previously
    corrupted history before the new compounding logic takes over.
    """
    from models.database import ShadowPortfolio, ShadowPortfolioSnapshot

    today_str = date.today().isoformat()
    shadows = (
        db.query(ShadowPortfolio)
        .filter_by(workspace_id=workspace_id, shadow_type="ACTIVE_MODEL", is_active=True)
        .all()
    )
    results: list[dict[str, Any]] = []
    for shadow in shadows:
        result: dict[str, Any] = {"shadow_id": shadow.id, "portfolio_id": shadow.portfolio_id}
        try:
            db.query(ShadowPortfolioSnapshot).filter_by(shadow_portfolio_id=shadow.id).delete()

            holdings: list[dict] = []
            if shadow.inception_holdings_json:
                try:
                    holdings = json.loads(shadow.inception_holdings_json)
                except Exception:
                    pass

            current_nav = 0.0
            if holdings:
                syms = [h["symbol"] for h in holdings if h.get("symbol")]
                prices = _fetch_cached_prices(db, syms)
                current_nav, _ = _compute_paper_value(holdings, prices)
                current_nav += shadow.paper_cash_balance or 0.0

            if current_nav < 1.0:
                current_nav = shadow.inception_value or 0.0

            shadow.inception_date = today_str
            shadow.inception_value = current_nav if current_nav > 0 else None
            shadow.inception_return_pct = 0.0
            shadow.current_value = current_nav if current_nav > 0 else None
            db.commit()

            if current_nav > 0:
                value_shadow_portfolio(db, shadow.id)

            result.update(
                status="reset",
                new_inception_date=today_str,
                new_inception_value=round(current_nav, 2),
            )
            logger.info(
                "[SHADOW] Reset ACTIVE_MODEL id=%s: new inception %s @ %.2f NAV",
                shadow.id, today_str, current_nav,
            )
        except Exception as exc:
            db.rollback()
            logger.error("[SHADOW] reset failed for shadow_id=%s: %s", shadow.id, exc)
            result.update(status="error", error=str(exc))
        results.append(result)
    return results


# ─── Historical regeneration (Accounting Correctness Milestone 2) ────────────
#
# Milestone 1 fixed the shared replay functions so future rebalances stop
# leaking cash, but explicitly left already-persisted ShadowPortfolioSnapshot
# rows and ShadowPortfolio.paper_cash_balance values untouched. The functions
# below re-derive those derived rows through the corrected engine. They never
# touch RecommendationSnapshot, PortfolioSnapshot, PortfolioItem, Transaction,
# UserExecutionDecision, or a shadow's inception_date/inception_value — only
# ShadowPortfolio.paper_cash_balance/inception_holdings_json/current_value/
# inception_return_pct and ShadowPortfolioSnapshot rows are rewritten.

def regenerate_static_shadow(db: Session, shadow_id: int, dry_run: bool = False) -> dict[str, Any]:
    """Re-derive paper cash + snapshot history for one STATIC_FROZEN shadow.

    dry_run=True computes and flushes every change (so it is fully validated
    — including the assert_nav_conserved calls below — against real DB
    state) then rolls back instead of committing, leaving the database
    unchanged. This is what backs the CLI's default preview mode.

    Covers both decision-keyed STATIC_FROZEN shadows and recommendation-keyed
    ones (execution_decision_id NULL) — both store target_weight_pct per
    holding in inception_holdings_json, which is the immutable record of what
    was decided (Design Invariant 1, OPTIMIZER_PHILOSOPHY.md §14, applied by
    analogy to shadows). Regeneration never re-derives weights from a live
    RecommendationSnapshot/UserExecutionDecision or from current PortfolioItem
    state — doing so would not reproduce history (PortfolioItem holdings and
    live prices may have changed since); instead it recomputes the cash
    residual directly from the ALREADY-STORED per-holding target_weight_pct
    values, which the original cash-leak bug never touched (only the missing
    cash bookkeeping was defective, never the weights/shares themselves).

        cash = max(0, (100 - sum(stored target_weight_pct)) / 100 * inception_value)

    Holdings never change after creation for this shadow_type, so once cash
    is corrected the existing _rebuild_shadow_snapshots (already used by
    repair_shadow_portfolios and create_recommendation_shadow's backfill
    path) replays the full daily history correctly — reused here rather than
    reimplemented (ENGINEERING_PRINCIPLES.md "Reuse Before Create").
    """
    from models.database import ShadowPortfolio

    shadow = db.query(ShadowPortfolio).filter_by(id=shadow_id).first()
    if not shadow:
        return {"status": "shadow_not_found", "shadow_id": shadow_id}
    if shadow.shadow_type != "STATIC_FROZEN":
        return {"status": "not_static_frozen", "shadow_id": shadow_id, "shadow_type": shadow.shadow_type}

    try:
        holdings = json.loads(shadow.inception_holdings_json) if shadow.inception_holdings_json else []
    except Exception:
        holdings = []
    if not holdings:
        return {"status": "skipped_no_holdings", "shadow_id": shadow_id}

    inception_value = shadow.inception_value or 0.0
    if inception_value <= 0:
        return {"status": "skipped_no_inception_value", "shadow_id": shadow_id}

    deployed_weight = sum(float(h.get("target_weight_pct") or 0) for h in holdings)
    cash = max(0.0, (100.0 - deployed_weight) / 100.0 * inception_value)

    # {} forces every holding to value at its own stored inception_price —
    # the immutable per-holding valuation locked at creation time, never a
    # live price lookup (regeneration must reproduce history, not re-price it).
    equity_at_inception, _ = _compute_paper_value(holdings, {})
    assert_nav_conserved(
        label=f"regenerate_static_shadow shadow_id={shadow_id}",
        expected_nav=inception_value, equity=equity_at_inception, cash=cash,
    )

    prev_cash = shadow.paper_cash_balance
    shadow.paper_cash_balance = cash

    history = _snapshot_price_history(db)
    rewritten = 0
    if history:
        rewritten = _rebuild_shadow_snapshots(db, shadow, holdings, history)

    if dry_run:
        db.flush()
        db.rollback()
    else:
        db.commit()

    logger.info(
        "[SHADOW REGEN]%s static shadow_id=%s: cash %.2f -> %.2f, %d snapshots rewritten",
        " [DRY RUN]" if dry_run else "", shadow_id, prev_cash or 0.0, cash, rewritten,
    )
    return {
        "status": "regenerated",
        "shadow_id": shadow_id,
        "prev_cash": prev_cash,
        "new_cash": cash,
        "snapshots_rewritten": rewritten,
        "dry_run": dry_run,
    }


def _replay_active_model_series(
    db: Session,
    portfolio_id: int,
    shadow: Any,
) -> dict[str, Any]:
    """Pure re-derivation of one ACTIVE_MODEL shadow's full daily NAV series.

    Read-only: issues DB queries but writes nothing, so it may be called any
    number of times (see verify_deterministic_replay). Walks every
    RecommendationSnapshot for *portfolio_id* from the shadow's immutable
    inception_date forward, applying the identical rebalance mechanic
    create_active_model_shadow uses live (_resolve_shares_from_weights +
    assert_nav_conserved) — mirrors ideal_series.py's day-by-day replay
    shape, but anchored to a real shadow's immutable inception_date/
    inception_value instead of a rolling period window, producing one row
    per calendar day of price history rather than an indexed-to-100 series.

    The seed allocation is the earliest RecommendationSnapshot on/before
    inception_date — by construction this is the exact snapshot that
    triggered the shadow's creation (main.py's optimizer-run handler writes
    the snapshot and creates/rebalances the shadow in the same request; see
    ideal_series.py's module docstring, "Rebalance-event-sequence
    alignment," for the verified call-site evidence). Every later snapshot
    is a rebalance point, identical to compute_ideal_series's rebalance_map.

    Every single regenerated day — not just rebalance points — is checked
    against assert_nav_conserved (Milestone 2's explicit "verify NAV ==
    Equity + Cash for every regenerated paper portfolio" requirement); by
    construction this can never fire, the same tripwire convention
    PORTFOLIO_CALCULATION_RULES.md §9 already documents for the real-ledger
    NAV reconciliation check.

    Each series row also carries that day's enriched holdings (the same
    shares/current_price/market_value shape value_shadow_portfolio already
    persists to ShadowPortfolioSnapshot.holdings_json) so the caller can
    write holdings_json/total_value/return fields from one consistent state
    instead of only updating total_value (Issue A, Accounting Correctness
    C5 — see regenerate_active_model_shadow).
    """
    from models.database import RecommendationSnapshot

    inception_date = shadow.inception_date
    inception_value = shadow.inception_value or 0.0
    empty = {"status": "", "dates": [], "series": [], "rebalance_dates": [],
             "final_holdings": [], "final_cash": 0.0, "inception_value": inception_value}
    if inception_value <= 0:
        return {**empty, "status": "skipped_no_inception_value"}

    rows = (
        db.query(RecommendationSnapshot)
        .filter(
            RecommendationSnapshot.portfolio_id == portfolio_id,
            RecommendationSnapshot.projected_allocations_json.isnot(None),
        )
        .order_by(RecommendationSnapshot.created_at.asc())
        .all()
    )
    parsed: list[tuple[str, list[dict]]] = []
    for r in rows:
        if not r.created_at:
            continue
        try:
            allocs = json.loads(r.projected_allocations_json)
        except Exception:
            continue
        if not allocs:
            continue
        parsed.append((r.created_at.date().isoformat(), allocs))

    seed: tuple[str, list[dict]] | None = None
    rebalances: list[tuple[str, list[dict]]] = []
    for d, allocs in parsed:
        if d <= inception_date:
            seed = (d, allocs)
        else:
            rebalances.append((d, allocs))

    if seed is None:
        return {**empty, "status": "no_seed_snapshot"}

    history = _snapshot_price_history(db)
    if not history:
        return {**empty, "status": "no_price_history"}

    period_end = date.today().isoformat()
    dates = sorted(d for d in history if inception_date <= d <= period_end)
    if not dates:
        return {**empty, "status": "no_price_dates"}

    rebalance_map = {d: allocs for d, allocs in rebalances}
    _, seed_allocs = seed

    seed_symbols = [a.get("symbol") for a in seed_allocs if a.get("symbol")]
    seed_prices = {
        sym: p for sym in seed_symbols
        if (p := _price_near_date(history, inception_date, sym))
    }

    holdings, cash = _resolve_shares_from_weights(seed_allocs, inception_value, seed_prices)
    deployed_value, _ = _compute_paper_value(holdings, seed_prices)
    assert_nav_conserved(
        label=f"regenerate_active_model_shadow seed portfolio_id={portfolio_id} date={inception_date}",
        expected_nav=inception_value, equity=deployed_value, cash=cash,
    )

    series: list[dict[str, Any]] = []
    last_prices: dict[str, float] = dict(seed_prices)

    for d in dates:
        last_prices.update(history.get(d, {}))

        if d in rebalance_map and d != inception_date:
            equity_before, _ = _compute_paper_value(holdings, last_prices)
            nav = equity_before + cash
            if nav <= 0:
                nav = series[-1]["total_value"] if series else inception_value
            new_symbols = [a.get("symbol") for a in rebalance_map[d] if a.get("symbol")]
            for s in new_symbols:
                if s not in last_prices:
                    p = _price_near_date(history, d, s)
                    if p:
                        last_prices[s] = p
            holdings, cash = _resolve_shares_from_weights(rebalance_map[d], nav, last_prices)
            deployed_value, _ = _compute_paper_value(holdings, last_prices)
            assert_nav_conserved(
                label=f"regenerate_active_model_shadow rebalance portfolio_id={portfolio_id} date={d}",
                expected_nav=nav, equity=deployed_value, cash=cash,
            )

        equity_today, enriched_today = _compute_paper_value(holdings, last_prices)
        total = equity_today + cash
        if total <= 0:
            total = series[-1]["total_value"] if series else inception_value

        assert_nav_conserved(
            label=f"regenerate_active_model_shadow day portfolio_id={portfolio_id} date={d}",
            expected_nav=total, equity=equity_today, cash=cash,
        )

        # holdings snapshot at this date's own valuation — persisted verbatim as
        # this row's holdings_json (see regenerate_active_model_shadow) so
        # holdings_json/total_value/return fields all describe one consistent
        # state, matching value_shadow_portfolio's existing enriched-holdings
        # convention (Issue A, Accounting Correctness C5).
        series.append({"date": d, "total_value": round(total, 6), "holdings": enriched_today})

    return {
        "status": "ok",
        "dates": dates,
        "series": series,
        "rebalance_dates": sorted(rebalance_map.keys()),
        "final_holdings": holdings,
        "final_cash": round(cash, 6),
        "inception_value": inception_value,
    }


def regenerate_active_model_shadow(db: Session, portfolio_id: int, dry_run: bool = False) -> dict[str, Any]:
    """Re-derive one portfolio's ACTIVE_MODEL shadow full snapshot history.

    dry_run=True flushes every computed change (so it is fully validated
    against real DB state, including per-day assert_nav_conserved checks in
    _replay_active_model_series) then rolls back instead of committing.

    Unlike regenerate_static_shadow, ACTIVE_MODEL holdings change at every
    rebalance, so its history cannot be replayed from one fixed holdings set
    — this is why repair_shadow_portfolios has always explicitly skipped
    ACTIVE_MODEL (see that function's docstring). This function computes the
    corrected series via the pure _replay_active_model_series, then persists
    it: inception_date/inception_value are never touched; only
    ShadowPortfolioSnapshot rows (upserted by the existing unique
    (shadow_portfolio_id, snapshot_date) constraint — never duplicated) and
    the shadow's current inception_holdings_json/paper_cash_balance/
    current_value/inception_return_pct are rewritten.

    Each upserted row's holdings_json is written from that same replay row
    (Issue A fix, Accounting Correctness C5): previously only total_value/
    return_pct_since_inception/daily_return_pct were refreshed on an
    existing row, leaving holdings_json at whatever it was before
    regeneration — internally inconsistent with the corrected total_value.
    holdings_json now always describes the same regenerated state as the
    other three fields, on every row, new or existing.
    """
    from models.database import ShadowPortfolio, ShadowPortfolioSnapshot

    shadow = (
        db.query(ShadowPortfolio)
        .filter_by(portfolio_id=portfolio_id, shadow_type="ACTIVE_MODEL", is_active=True)
        .order_by(ShadowPortfolio.created_at.desc())
        .first()
    )
    if not shadow:
        return {"status": "no_active_model_shadow", "portfolio_id": portfolio_id}

    replay = _replay_active_model_series(db, portfolio_id, shadow)
    if replay.get("status") != "ok":
        return {"status": replay.get("status"), "portfolio_id": portfolio_id, "shadow_id": shadow.id}

    existing_rows = {
        s.snapshot_date: s
        for s in db.query(ShadowPortfolioSnapshot)
        .filter(ShadowPortfolioSnapshot.shadow_portfolio_id == shadow.id)
        .all()
    }

    inception_value = replay["inception_value"]
    prev_total: float | None = None
    written = 0
    for row in replay["series"]:
        d, total = row["date"], row["total_value"]
        # Issue A (Accounting Correctness C5): holdings_json must describe the
        # same regenerated state as total_value/the return fields below —
        # never left stale on an existing row. See _replay_active_model_series.
        holdings_json = json.dumps(row["holdings"], default=str)

        inception_ret: float | None = None
        if inception_value:
            raw_ret = (total - inception_value) / inception_value * 100
            if -99.9 <= raw_ret <= 1000.0:
                inception_ret = round(raw_ret, 4)

        daily_ret: float | None = None
        if prev_total and prev_total > 0:
            raw_daily = (total - prev_total) / prev_total * 100
            if -50.0 <= raw_daily <= 50.0:
                daily_ret = round(raw_daily, 4)
        prev_total = total

        existing = existing_rows.get(d)
        if existing:
            existing.total_value = total
            existing.return_pct_since_inception = inception_ret
            existing.daily_return_pct = daily_ret
            existing.holdings_json = holdings_json
        else:
            db.add(ShadowPortfolioSnapshot(
                shadow_portfolio_id=shadow.id,
                snapshot_date=d,
                total_value=total,
                return_pct_since_inception=inception_ret,
                daily_return_pct=daily_ret,
                holdings_json=holdings_json,
                benchmark_symbol=_BENCHMARK_SYMBOL,
                created_at=datetime.utcnow(),
            ))
        written += 1

    final_total = replay["series"][-1]["total_value"] if replay["series"] else shadow.current_value
    shadow.inception_holdings_json = json.dumps(replay["final_holdings"], default=str)
    shadow.paper_cash_balance = replay["final_cash"]
    shadow.current_value = final_total
    if inception_value and final_total is not None:
        raw = (final_total - inception_value) / inception_value * 100
        if -99.9 <= raw <= 1000.0:
            shadow.inception_return_pct = round(raw, 4)

    if dry_run:
        db.flush()
        db.rollback()
    else:
        db.commit()

    logger.info(
        "[SHADOW REGEN]%s ACTIVE_MODEL portfolio_id=%s shadow_id=%s: %d snapshots written, "
        "%d rebalances replayed, final_cash=%.2f",
        " [DRY RUN]" if dry_run else "", portfolio_id, shadow.id, written,
        len(replay["rebalance_dates"]), replay["final_cash"],
    )
    return {
        "status": "regenerated",
        "portfolio_id": portfolio_id,
        "shadow_id": shadow.id,
        "snapshots_written": written,
        "rebalances_replayed": len(replay["rebalance_dates"]),
        "final_cash": replay["final_cash"],
        "dry_run": dry_run,
    }


def regenerate_portfolio_paper_history(
    db: Session, portfolio_id: int, workspace_id: int, dry_run: bool = False,
) -> dict[str, Any]:
    """Orchestrate full paper-portfolio regeneration for one portfolio.

    Regenerates every STATIC_FROZEN-family shadow (decision-keyed and
    recommendation-keyed alike) plus the ACTIVE_MODEL shadow, if present.
    Each shadow is regenerated independently (its own flush/commit or
    flush/rollback boundary) and a failure is captured per-shadow rather
    than aborting the whole portfolio (ENGINEERING_PRINCIPLES.md "Failure
    Handling" — a degraded shadow must be observable, never fatal to its
    siblings). Does not touch AttributionMetric — see module docstring for
    why that is a separate, caller-driven refresh.
    """
    from models.database import ShadowPortfolio

    results: dict[str, Any] = {
        "portfolio_id": portfolio_id,
        "dry_run": dry_run,
        "static_shadows": [],
        "active_model": None,
        "errors": [],
    }

    static_shadows = (
        db.query(ShadowPortfolio)
        .filter_by(portfolio_id=portfolio_id, shadow_type="STATIC_FROZEN")
        .order_by(ShadowPortfolio.id)
        .all()
    )
    for s in static_shadows:
        try:
            r = regenerate_static_shadow(db, s.id, dry_run=dry_run)
        except Exception as exc:
            db.rollback()
            logger.error("[SHADOW REGEN] static shadow_id=%s failed: %s", s.id, exc)
            r = {"status": "error", "shadow_id": s.id, "error": str(exc)}
            results["errors"].append(r)
        results["static_shadows"].append(r)

    try:
        results["active_model"] = regenerate_active_model_shadow(db, portfolio_id, dry_run=dry_run)
    except Exception as exc:
        db.rollback()
        logger.error("[SHADOW REGEN] active model portfolio_id=%s failed: %s", portfolio_id, exc)
        results["active_model"] = {"status": "error", "portfolio_id": portfolio_id, "error": str(exc)}
        results["errors"].append(results["active_model"])

    return results
